app1/urls.py
from django.urls import path
from app1.views import *
app_name='abbu'
urlpatterns=[
    path('a1/',a1,name='a1'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='bakar'
urlpatterns=[
    path('a2/',a2,name='a2'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def a1(request):
    return render(request,'a1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def a2(request):
    return render(request,'a2.html')

templates/a1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>a1 html</title>
</head>
<body>
    <center>
        <h1>THIS IS APP1 HTML PAGE</h1>
        <h2>
            <a href="{% url 'bakar:a2' %}">goto a2</a>
        </h2> 
    </center>
</body>
</html>

templates/a2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>a2 html</title>
</head>
<body>
    <center>
        <h1>THIS IS APP2 HTML PAGE</h1>
        <h2><a href="{% url 'abbu:a1' %}">go to a1</a></h2>
    </center>
</body>
</html>